name: stake
description: "Memory Games - Premium Gaming Experience"
publish_to: 'none'

version: 1.0.1+6

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.0.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^8.0.0
  shared_preferences: ^2.2.2
  http: ^1.2.0
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/app_icons/